### ISSUE TITLE
Problem with accessing the number of pages

### ISSUE THREAD

**Issue by superaeropowerful** [supercoderz/pyflightdata#11]
Hallo,
I found a problem when running the code, and I don't understand if there is something that I am doing wrong or it is a bug. I have a Gold Account, so theoretically I should have access to 365 days flight data. Nevertheless, I realized that when choosing manually the page number in:
´´´fr.get_history_by_flight_number('N12028', limit=100, page=2)´´´
the result does not change for pages > 2. If I put page=3 or page=4 I get the same answer as when page=2.
I would really appreciate if you could help me understanding this.
Regards!
N.

**Comment by hari-allamraju** [comment]
Will check and get back

Thanks,
Hari

**Comment by hari-allamraju** [comment]
It appears that limit overrides page number - for example with a silver membership I can see 93 results for TR574. If I pass a limit over 100, I get 0 results, and if I reduce the limit to say 10 and try to get page 2 - I still get the first 10 results.

Have to see if there is a way around this issue since there are no official API docs from FR24

**Comment by dmoraine** [comment]
Hello,

To get the results from page > 1, you need to add a parameter _timestamp_ to the URL. 

For the page 1:
`'https://api.flightradar24.com/common/v1/flight/list.json?query={0}&fetchBy=reg&page={2}&limit={3}&token={1}'`

For page > 1:
`'https://api.flightradar24.com/common/v1/flight/list.json?query={0}&fetchBy=reg&page={2}&limit={3}&token={1}&timestamp={4}'`

The value `{4}` has to be taken from the last entry of the previous page under `['time']['other']['updated']`.

**Comment by dmoraine** [comment]
A quick and dirty fix : 

```
diff --git a/pyflightdata/common_fr24.py b/pyflightdata/common_fr24.py
index 8e867ea..2b88505 100644
--- a/pyflightdata/common_fr24.py
+++ b/pyflightdata/common_fr24.py
@@ -24,7 +24,7 @@ from .common import ProcessorMixin
 from .json_helper import fltr
 
 ROOT = 'http://www.flightradar24.com'
-REG_BASE = 'https://api.flightradar24.com/common/v1/flight/list.json?query={0}&fetchBy=reg&page={2}&limit={3}&token={1}'
+REG_BASE = 'https://api.flightradar24.com/common/v1/flight/list.json?query={0}&fetchBy=reg&page={2}&limit={3}&token={1}&timestamp={4}'
 FLT_BASE = 'https://api.flightradar24.com/common/v1/flight/list.json?query={0}&fetchBy=flight&page={2}&limit={3}&token={1}'
 AIRPORT_BASE = 'http://www.flightradar24.com/data/airports/{0}'
 AIRPORT_DATA_BASE = 'https://api.flightradar24.com/common/v1/airport.json?code={0}&page={2}&limit={3}&token={1}'
@@ -41,6 +41,8 @@ class FR24(ProcessorMixin):
 
     FILTER_JSON_KEYS = ['hex', 'id', 'logo', 'row', 'icon']
 
+    timestamp = ""
+
     # airport stats
 
     def filter_and_get_data(self, data):
@@ -110,6 +112,9 @@ class FR24(ProcessorMixin):
 
     def process_raw_flight_data(self, data, by_tail=False):
         # TODO check later if we need to parse this data - for now return full set
+        l = len(data)
+        self.timestamp = ""
+        if l > 0: self.timestamp = data[l-1]['time']['other']['updated']
         return data
 
     def get_data(self, url, by_tail=False):
diff --git a/pyflightdata/flightdata.py b/pyflightdata/flightdata.py
index b6f8796..6c73261 100644
--- a/pyflightdata/flightdata.py
+++ b/pyflightdata/flightdata.py
@@ -108,7 +108,8 @@ class FlightData(FlightMixin):
             f.get_history_by_flight_number('VT-ANL',page=1,limit=10)
 
         """
-        url = REG_BASE.format(tail_number, str(self.AUTH_TOKEN), page, limit)
+        url = REG_BASE.format(tail_number, str(self.AUTH_TOKEN), page, limit, self._fr24.timestamp)
         return self._fr24.get_data(url, True)
 
     def get_countries(self):
```

**Comment by hari-allamraju** [comment]
Can you do a pull request with this change?

**Comment by hari-allamraju** [comment]
Will be fixed in next release thanks to PR from @dmoraine
