### ISSUE TITLE
get_airports() seem broken

### ISSUE THREAD

**Issue by E3V3A** [supercoderz/pyflightdata#13]
@hari-allamraju 

I'm trying to get the list of airports in a country, but since recently it return an empty list. :(

```bash
# python3 -c "from pyflightdata import FlightData as fd; a=fd().get_airports('Denmark'); print(a);"
[]
```

Did they kill this API function for us?

**Comment by E3V3A** [comment]
Sorry, I was using 0.5.6, and it seem something was updated since. Now it works.

**Comment by hari-allamraju** [comment]
This keeps breaking every now and then because this is a page scrape - will try to check this on the weekend
