### ISSUE TITLE
I have created a great CLI using this library

### ISSUE THREAD

**Issue by E3V3A** [supercoderz/pyflightdata#14]
@hari-allamraju 
Please consider adding a link to your README and try out my CLI using this library. 

* [iata-arrivals-cli](https://github.com/E3V3A/iata-arrivals-cli) - Get airport arrivals, departures, details and METAR weather info from CLI 

Perhaps you have some suggestions for improving. 
I love this tool and use it almost everyday to check the weather and airport info. 

Cheers and many Thanks!
:1st_place_medal:  :heart:  :tada:

**Comment by hari-allamraju** [comment]
Great! I will definitely add a link in the README and try out the tool!
