### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by ArchieGu** [supercoderz/pyflightdata#15]
Hi, Here is my problem:

I have followed the document and don't know where the problem is:
![Screen Shot 2019-05-29 at 5 05 48 PM](https://user-images.githubusercontent.com/19317957/58544526-0c6ea980-8234-11e9-8016-ec81540c39c2.png)
here is my code:
`f.login('xxxx@gmail.com','xxxxxxxxx')`

**Comment by hari-allamraju** [comment]
Cannot reproduce at my end - might have been a FR24 glitch
