### ISSUE TITLE
The flight has no CALIBRATED ALTITUDE 

### ISSUE THREAD

**Issue by toilv** [supercoderz/pyflightdata#16]

**Comment by toilv** [comment]
'position': {'country': {'code': 'IN', 'name': 'India'},
     'latitude': '28.5665',
     'longitude': '77.103081',
     'region': {'city': 'Delhi'}},

**Comment by hari-allamraju** [comment]
This is probably a FR24 glitch - the API just gets the data as provided and does not do any calculatiohns.
