### ISSUE TITLE
Two-Worded Countries Not Returning Airports

### ISSUE THREAD

**Issue by wahooo-2** [supercoderz/pyflightdata#2]
I am using api.get_airports(country) to get all of the airports in a given country. It works for countries whose name are just one word (Angola, France, etc.), but it just returns an empty list for countries that have two words in the name (French Polynesia, United Kingdom, United States, etc.). Any ideas on why this is and how I can work around it?

**Comment by hari-allamraju** [comment]
Hi,

Can you raise this as a bug on Github? I will take a look at this and get back to you as soon as I can.
I recently made some changes to the API to handle some changes on FR24 side - might have been broken during that

Thanks,
Hari

**Comment by hari-allamraju** [comment]
This is fixed in version 0.5.3 - please update from pypi and check again
