### ISSUE TITLE
issue when  get_airport_departures(iata, page=1, limit=100, earlier_data=True)

### ISSUE THREAD

**Issue by chauvanphuoc** [supercoderz/pyflightdata#20]
Dear, the function  get_airport_departures was error when select "earlier_data=True"

**Comment by hari-allamraju** [comment]
Can you give me the full code sample and the error?

**Comment by hari-allamraju** [comment]
@chauvanphuoc I have tried this for SIN with my latest code, includes fixes from today and it works fine.
If you can give me full error stack that you see, I can debug better

**Comment by chauvanphuoc** [comment]
Dear hari, sorry to reply late, I capture the error code as below:

![image](https://user-images.githubusercontent.com/13195922/67165177-2e67f480-f3ac-11e9-82bd-b189ff7f9dc7.png)

**Comment by hari-allamraju** [comment]
I tried this with the latest 0.7 release and I don't see the same problem. Do you want to try that and let me know? 0.7 fixes a few issues caused due to change in the HTML on FR24 pages

**Comment by chauvanphuoc** [comment]
Thank you very much Hari. It is working now. Kindly regards,

**Comment by RenaTorelli** [comment]
Dear Hari,
unfortunately I have the same error but with the version 0.8!
Here is the code:

**from pyflightdata import FlightData
api=FlightData()
api.get_airport_departures('PMF',page=1,limit=4,earlier_data=True)**

and here is the trace:

**File "C:\Users\renat\anaconda3\lib\site-packages\pyflightdata\flightdata.py", line 498, in get_airport_departures
    url = AIRPORT_DATA_BASE_EARLIER.format(iata, str(self.AUTH_TOKEN), page, limit,int(datetime.date.today().strftime('%s')))**

**ValueError: Invalid format string**

**Comment by hari-allamraju** [comment]
Uploaded version 0.8.1 by changing how the UTC timestamp is created; added more OS tests in Travis to catch these better

**Comment by RenaTorelli** [comment]
Wonderful, it works! You are really great. I don't have enough words to express my thanks ;-)

**Comment by hari-allamraju** [comment]
No problem at all 👍

Thanks,
Hari

**Comment by RenaTorelli** [comment]
Dear Hari,
method get_airport_details() works very well with many airport codes  (e.g. get_airport_details('FCO')) instead sometimes I get an error. For example, if I use the code 'EBA' (always obtained using get_airports('Italy')) I get an error. Here is the error I got using get_airport_details('EBA')):

**Traceback (most recent call last):

  File "C:\MYDIR\Program.py", line 59, in <module>
    airport_details=api.get_airport_details(cod_airport)

  File "C:\Users\myname\anaconda3\lib\site-packages\pyflightdata\flightdata.py", line 415, in get_airport_details
    details['position']['elevation'] = weather['elevation']

TypeError: list indices must be integers or slices, not str**

I thank you in advance,
Renato

**Comment by hari-allamraju** [comment]
Sorry for the delay in looking at this. It appears that there is no weather information for this airport. The elevation information for the airport is more accurate in weather and so airport details depends on that to get the elevation.

I will release a fix today to return blank weather and thus not depend on that to get elevation.
Hopefully that will prevent the code from breaking of you are for example getting information about airports in a loop. You would have to handle not see some data for the airport in your code


Thanks,
Hari

**Comment by RenaTorelli** [comment]
I tested the new version. It works perfectly! Thanks Hari, you are great!
My best regards,
R.
