### ISSUE TITLE
error in get_airport_details

### ISSUE THREAD

**Issue by TomOnGit** [supercoderz/pyflightdata#23]
`from pyflightdata import FlightData`
`f=FlightData()`
`print(f.get_airport_details('ICY'))`

gives the following error:

> line 377, in get_airport_details
>     details['position']['elevation'] = weather['elevation']
> TypeError: list indices must be integers or slices, not str

**Comment by hari-allamraju** [comment]
is ICY a valid code? I am unable to find that on flightradar as well. If there is an error instead of data then you are likely to see this error

**Comment by hari-allamraju** [comment]
No updates on this issue in a long time
