### ISSUE TITLE
Limit 100 and Page 1 is a maximum

### ISSUE THREAD

**Issue by ykhromov** [supercoderz/pyflightdata#25]
Hi! Thanks for you library, it's amaizing! Lib saved a lot of my time. 
But I have one issue. 

In every request I run, limit stays on 100 and I can't get more than 1 page. 
I have got an account on F24, of course.

Here is the example of my code. I'll be very pleased, if you can help me to get all data. 
Before left this issue I have been read all closed issues.

```
f=FlightData()
f.login(login, password)

history = []
for page in range(5):
    history.append(f.get_history_by_flight_number('3v284', page=page))
    time.sleep(1)
```

**Comment by hari-allamraju** [comment]
Hi - please refer to this issue and try that approach for page > 1. Please note that this will work as long as FR24 doesnt change their pages again. My library only works like a wrapper over API calls they use for showing the pages, it is not official and so is prone to breaking occasionally

https://github.com/supercoderz/pyflightdata/issues/11
