### ISSUE TITLE
flight routes

### ISSUE THREAD

**Issue by DavidSamir907** [supercoderz/pyflightdata#28]
hello thanks for the previous answer

I have the FR24 gold subscription and in this I was able to obtain the flight paths (latitude, longitude and height), I would like to know if with your code and my account I could obtain that information

**Comment by hari-allamraju** [comment]
Hi - the API is just a wrapper over HTTP. It returns all the data you can see on screen, however things like flight path or the download links are not supported. There were issues with getting that.
