### ISSUE TITLE
answer from f.get_flights nearly empty

### ISSUE THREAD

**Issue by kopfpolster** [supercoderz/pyflightdata#29]
first of all: thank you for this nice app! good work!

i got it to work, it answers this example niceliy:

```
vieinfo = f.get_airport_details('VIE', page=1, limit=1)
print (vieinfo)
```
so the connection seems to work.

but if i try **fluginfo = f.get_flights(flugnr)** 
(flugnr is a variable, now it is 'QTR5MP')

i get: 

```
DEBUG:urllib3.connectionpool:https://www.flightradar24.com:443 "GET /v1/search/web/find?query=QTR5MP&limit=100&type=schedule HTTP/1.1" 200 None
[{'label': 'QR291', 'detail': {'callsign': 'QTR5MP', 'flight': 'QR291'}, 'type': 'schedule', 'match': 'begins'}]
```

is this a pyflightdata issue?
thanks!

**Comment by hari-allamraju** [comment]
This happens when FR24 does not return data; since pyflightdata is just a wrapper over HTTP it cannot handle this. Best is to retry in your code.
