### ISSUE TITLE
get_flights('emirates-ek-uae') not working any more for me

### ISSUE THREAD

**Issue by James-pyth0n** [supercoderz/pyflightdata#3]
Firstly thank you for a very useful python module.

Was working fine until a couple of days ago.
My use is to check 3 times a day on certain flights and gain their expected arrival times at our local airport
So I check all airline flights for emirates, check against a set of flight numbers to get the time of arrival
This is running on a raspberry pi, and the info is sent via pushetta to mobile device

it seems to fail at get_flights(emirates-ek-uae') as described below

version 0.3 (did try update on another machine and still same, so I do wonder if it is a flightradar24 problem?), 
last success 18/12/17

# sample code that would get other info from command line ok, ie get_fleet(emirates-ek-uae')

from pyflightdata import FlightData

api = FlightData()

>>> a = api.get_flights('emirates-ek-uae')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyflightdata/flightdata.py", line 44, in get_flights
    return self.fr24.get_airline_flight_data(url)
  File "/usr/local/lib/python2.7/dist-packages/pyflightdata/common_fr24.py", line 252, in get_airline_flight_data
    return self.process_raw_airline_flight_data(data)
  File "/usr/local/lib/python2.7/dist-packages/pyflightdata/common_fr24.py", line 239, in process_raw_airline_flight_data
    record['flight'] = self.encode_and_get(cells[1].text)
IndexError: list index out of range

Any reason for this or do I need a rethink of my search of flights??

Thank you

James

**Comment by hari-allamraju** [comment]
I am not seeing any data for the URL even when I try from fligtradar24 website, using a silver membership. This could be  temporary issue or a change to the underlying URL's.

I do keep falling behind these changes as this is not an official API - will check and try to fix the issue

**Comment by James-pyth0n** [comment]
OK. At least I know its not an issue with my or your code. Hopefully can be rectified. 
Since I wrote my flight tracker prog I have looked further into web scraping and have a working web scrape prog with beautifulsoup. This helped me read your code and understand it more.

**Comment by James-pyth0n** [comment]
I contacted flighradar24 who are looking into the problem, so hopefully you or I don't need to make any changes.
James

**Comment by hari-allamraju** [comment]
I pushed a new version to pypi which returns a blank list if there is an issue with the data on the flights page.

**Comment by James-pyth0n** [comment]
That helps with the error handling for me. My fall back routine is here 
[flightInfo](https://github.com/James-pyth0n/flightInfo)
Very grateful for your code it has helped me loads
James
