### ISSUE TITLE
get_history_by_flight_number sometimes returns an empty list

### ISSUE THREAD

**Issue by robroc** [supercoderz/pyflightdata#30]
First, thank you for this very helpful library.

I'm iterating through a list of flight numbers and calling `get_history_by_flight_number` without page number (I only need the first page). Sometimes the result is an empty list, seemingly at random. Most times the data is returned properly.

For example, this flight:
https://www.flightradar24.com/data/flights/ts824

When using the Flightradar24 API URL, the full data returns as well.

python==3.8.2
pyflightdata==0.8.5

**Comment by hari-allamraju** [comment]
This is a known issue with no solution - the API is just making HTTP calls to FR24’s unofficial json endpoints. So from time to time it gets throttled or fails to get any data. Workaround is to add a sleep in between calls - this could sometimes increase too

Thanks,
Hari
