### ISSUE TITLE
Would it be possible to detect special liveries?

### ISSUE THREAD

**Issue by lexd283** [supercoderz/pyflightdata#36]
--not an issue, just a suggestion, because i cannot find a reasonable way to contact you, sorry!--
Flightradar24 shows the special livery name on the "airline" name.
Honestly, it could be an awesome addition to this library! Maybe an extra dict in the FlightData
example:
`"special_livery":"Expo 2020 - Mobility Livery"`
If it isn't, then it returns null i guess

![image](https://user-images.githubusercontent.com/80298061/137503781-17c9280b-a970-489b-9a67-6bd51770f75b.png)
![image](https://user-images.githubusercontent.com/80298061/137503294-41c93290-fa4f-409f-9769-bbb045de1977.png)

**Comment by hari-allamraju** [comment]
The API is just a wrapper I built over FR24 and is not actually affiliated or owned by FR24. So unless there is a way to identify that the extra information on airline name is special livery information I am not sure we have a clean way to do this. We could parse by any info in parenthesis, but would that work in all cases? I am not sure.

If you want to try that and if you find it working with multiple airlines then feel free to do a pull request.
