### ISSUE TITLE
Can we get departure and arrival data as well?

### ISSUE THREAD

**Issue by E3V3A** [supercoderz/pyflightdata#4]
Can we get departure and arrival data as well?

**Comment by hari-allamraju** [comment]
Now that the API supports user login, it can be enhanced to fetch the Airport arrival/departure and other stats from this page - https://www.flightradar24.com/data/airports/sin

**Comment by E3V3A** [comment]
Cool, so what do I need to do to get that? 
Also, does it mean it's a paid service?

**Comment by hari-allamraju** [comment]
I need to make a code change to the API - will try to get it done this week

You don't need a paid plan on flightradar24 to access airports data, but that could change later in the future

I believe earlier this was not the case and do I did not include the functionality in the API

**Comment by hari-allamraju** [comment]
Updated the code and published version 0.5.5 to pypi - please check and let me know if that data works. At the moment I haven't filtered out any data and included almost everything that is shown on the arrivals/departures pages.

This works for both authenticated and un-authenticated sessions

**Comment by E3V3A** [comment]
@hari-allamraju  
This is awesome! Worked on the first try! I will definitely try to make something useful out of this. 

1. Although it doesn't matter, it seem a little funny that `lat` come first, and `lon` come second last in the list: 

```
{'lat': '16.53043', 'iata': 'VGA', 'lon': '80.796837', 'name': 'Vijayawada Airport'}
```
2. I get too many returned flights for the arrivals.  How can the result be best limited? 

```bash
/arrivals.py |json_pp -f json -t dumper -json_opt pretty,utf8,allow_singlequote |grep flight |wc -l
64
```
3. What is the formatting for the timestamps? 

```
'time' => {
                                      'estimated' => {
                                                       'departure' => 'None',
                                                       'arrival' => 'None'
                                                     },
                                      'scheduled' => {
                                                       'departure' => '1515263400',
                                                       'arrival' => '1515273000'
                                                     },
                                      'other' => {
                                                   'eta' => '1515271630',
                                                   'duration' => '7860'
                                                 },
                                      'real' => {
                                                  'departure' => '1515263757',
                                                  'arrival' => '1515271630'
                                                }
                                    },
                          'status' => {
                                        'generic' => {
                                                       'eventTime' => {
                                                                        'local' => '1515278830',
                                                                        'utc' => '1515271630'
                                                                      },
```
I guess they are Unix epoch time  since 1970-01-01...  `date --date='@1515396300`.

Thank you for doing this.

**Comment by hari-allamraju** [comment]
Yes the timestamps are in Unix epoch time, there is no code that converts that to UTC - simply to avoid overhead and because I have no idea how the data is being used at the moment.

The lat/lon issue - the code doesnt re-order any keys after getting the data from flightradar24 - could be looked at later.

There is a parameter called limit which can be passed to the methods and it will send you only that many results. This applies to all the methods. There is also a page parameter.

I have created a simple API doc for now, this will expand out later.

Please take a look here - http://pyflightdata.readthedocs.io/en/latest/index.html

**Comment by E3V3A** [comment]
@hari-allamraju Again thanks for making this! Awesome!
