### ISSUE TITLE
Elevation units are unknown or possibly wrong?

### ISSUE THREAD

**Issue by E3V3A** [supercoderz/pyflightdata#6]
Using the `elevation` from `get_airport_details` are in units of feet instead of in meters. This seem very US and non-standard for the int'l air industry. Also there is no mentioning of what the units are in the json. 

E.g. `BOG` from [here](https://en.wikipedia.org/wiki/List_of_highest_airports):
```
44 | El Dorado International Airport[30] | Bogotá | Colombia | BOG | SKBO | 04°42′5″N 74°8′49″W | 2,548 | 8,360
```

* My suggested fix is to convert to default output to meters.
* A better solution is to use `get_airport_weather` with `['elevation']['m']`. 

Also, many of those airports on that list are not available from this API, but there are no specific error messages... What can be the reasons why so many airports (with IATA codes) are not shown?

**Comment by hari-allamraju** [comment]
Will investigate the units - funny that we do get both feet and meters for airport weather, might just have to convert/replace

I dont think all airports will have data, only those that have some scheduled arrivals/departures and where there is data being recorded by fr24. Any specific examples that you tested? And was it with a user ID (paid plan?) or just un authenticated?

**Comment by E3V3A** [comment]
I basically just stopped using elevation from the get_airport_details. In addition I found some small discrepancies of the elevations stated by this API, versus other apis, sources. Unfortunately I don't recall for which airports. 

I've only tested without authentication, and so far no problem. I've never got any response that I am overloading or not allowed to. But then again I try not to send more than a few request per hour. 
There are plenty of airports not covered by data... E.g. `IPI, DCY, KGT, LXV`.

**Comment by hari-allamraju** [comment]
elevation in airport details now copies from the same field in airport weather which has both feet and meters

I am avoiding using any source other than flightradar24 for now.

It appears that the airports really dont have much data - will check later on using other sources etc

Please use latest version 0.5.6 for the fixes
